package extra; 

import java.io.IOException;

public class Exception_Test {
	

	static Integer f = new Integer(43);
	public Integer fhj = null;
	static int xnm = 42;

	
	public static void main(String... c)
	{
		
				
		
		String abc = "abcdf";
		abc = abc.trim(); 
		System.out.println(abc);
		
		
		Exception_Test test = new Exception_Test();
		///test.new Outer().inner();
		//test.Outer test2 = new test.Outer();
		
		String str = "10";
		
		//int a = new Integer(10);
		
		Integer a =10;
		str+= a; 
		
		boolean b = str == a+"";
		System.out.println(b);
		int i=0;
		Math.abs(i);
		
		long acc = 56567_542434l;
		long  ghg= 0xFF_DC;
		byte njb = 0b001_0101;
 System.out.println("abc".charAt(3));
		acc = acc + njb;
		
		
	//	Float item[] ={7,6,5};
		
		while(true && (7==7))
		{}
		
		
		
	}
	
	/*final int num = 456;
	
	class Outer
	{
		int num =123;
		
		void inner()
		{
			System.out.println();
		}
	}*/
	
}
